---
title: "rseo_journalism"
output: word_document
date: "2025-08-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
pacman::p_load(tidyverse, lubridate, ggbeeswarm, janitor)
source("chart_style.R")


```

## Load data

```{r read}

full_sample <- read_csv("data_read_in/classified_story_sample.csv")


all_sats <- read.delim("https://www.ucs.org/sites/default/files/2024-01/UCS-Satellite-Database%205-1-2023%20%28text%29.txt", sep = "\t") %>%
  clean_names() 

wavelengths <- read_csv("data_read_in/wavelengths.csv") %>%
  filter(!is.na(min_nm))


```
## Dates
```{r dates}

timeline <- full_sample %>%
  mutate(year = floor_date(date, "year")) %>%  # first day of month
  group_by(year) %>%
  arrange(classification) %>%
  mutate(y = row_number()) %>%
  ungroup()


ggplot(timeline, aes(x = date, y = y, colour = item_source)) +
  geom_point(size = 5) +
  scale_colour_manual(values = c(five_point[4], five_point[2]),
                      labels = c("Snowball sampling", "Sigma awards"))+
  rseo_style() +
  scale_x_date(breaks = as.Date(c("2015-01-01", "2017-01-01", "2019-01-01", "2021-01-01", "2023-01-01", "2025-01-01")),
    date_labels = "%Y") +
  theme(panel.grid.major.y = element_blank(),
        axis.ticks.x = element_line(),
        axis.text.y = element_blank(),
        legend.position = "right") +
  guides(colour = guide_legend(reverse=T)) +
  geom_hline(yintercept = 0)

ggsave("figures/timeline.png", width = 15, height = 10, units = "cm", dpi = 300)


country_count <- full_sample %>%
  group_by(country) %>%
  summarise(count = n()) %>%
  arrange(desc(count), country)


ggplot(full_sample %>% group_by(country) %>%
  summarise(y = row_number()) %>% ungroup() %>%
    mutate(country = factor(country, levels = rev(c("United States",
                                                "United Kingdom",
                                                "Ukraine",
                                                "Brazil",
                                                "France",
                                                "Qatar",
                                                "Singapore",
                                                "Australia",
                                                "Botswana",
                                                "Canada",
                                                "Germany",
                                                "Jordan",
                                                "Switzerland",
                                                "Uruguay")))), 
  aes(x = y, y = country)) + 
  geom_tile(colour = "white", fill = alt_cols_five[1]) +
  rseo_style() +
  coord_fixed() +
  geom_vline(xintercept = 0, colour = "black") +
  theme(panel.grid.major.y = element_blank(),
        axis.text.x = element_blank())

ggsave("figures/countries.png", width = 15, height = 10, units = "cm", dpi = 300)





```


## Classification plot
The classification results show a fairly even distribution across the categories, 

```{r pressure, echo=FALSE}

by_cat <- full_sample %>%
  group_by(classification) %>%
  arrange(networked) %>%
  mutate(y = row_number()) %>%
  ungroup() %>%
  mutate(classification = factor(classification, levels = c("Illustrative", "Evidentiary", "Investigative", "Hybrid", "Experimental")))


ggplot(by_cat, aes(x = y, y = classification, fill = classification, colour = networked)) + 
  geom_tile(aes(fill = classification), show.legend = FALSE) +
  geom_tile(data = by_cat %>% filter(networked == "yes"),
            aes(x = y, y = classification, colour = networked),
            fill = NA, size = 1, colour = "black", show.legend = FALSE) +  # Outline layer
          
  rseo_style() +
  coord_fixed() +
  scale_fill_manual(values = five_point, guide = "none") +
  scale_colour_manual(values = c("black", "white")) +
  theme(panel.grid.major.y = element_blank(),
        axis.text.x = element_blank()) 

ggsave("figures/classification.png", width = 15, height = 10, units = "cm", dpi = 300)





```


## modality
```{r modallity} 
    

modality <- separate_rows(full_sample, operative_use, convert = TRUE)


ggplot(modality %>% drop_na(pub_private_both) %>%
         mutate(pub_private_both = factor(pub_private_both, levels = c("Public", "Both", "Commercial"))), aes(x = classification, fill = pub_private_both)) +
  geom_bar(position = "fill") +
  rseo_style() +
  coord_flip() +
  scale_fill_manual(values = c(five_point[1], five_point[4], five_point[2])) +
  scale_y_continuous(labels = scales::percent, breaks = c(0, 0.5, 1)) +
  theme(legend.position = "right",
        panel.grid.major.y = element_blank()) +
  labs(title = "Data source by provider",
       subtitle = " ")


pub_com <- separate_rows(modality, pub_private, convert = TRUE)



ggplot(pub_com %>% drop_na(pub_private) %>%
         mutate(pub_private = factor(pub_private, levels = c("Public", "Both", "Commercial"))), aes(x = classification, fill = pub_private)) +
  geom_bar(position = "fill") +
  rseo_style() +
  coord_flip() +
  scale_fill_manual(values = c(five_point[2], five_point[5])) +
  scale_y_continuous(labels = scales::percent, breaks = c(0, 0.5, 1)) +
  theme(legend.position = "right",
        panel.grid.major.y = element_blank()) +
  labs(title = "Data source by provider",
       subtitle = " ")



modality_grid <- modality %>%
  select(classification, operative_use) %>%
  group_by(classification, operative_use) %>%
  summarise(n = n(),
            sqrt = sqrt(n())) %>%
  mutate(sq = floor(sqrt))

modality_grid <- modality %>%
  group_by(classification, operative_use) %>%
  arrange(derived_data_product) %>%
  mutate(obs_id = row_number()) %>%
  mutate(n = n(),
         sq = ceiling(sqrt(n))) %>%
  mutate(
    x = ((obs_id - 1) %% sq) + 1,              # x increases across the row
    y = (floor((obs_id - 1) / sq)) + 1         # y increases down the column
  ) %>%
  ungroup()

source_num <- modality %>%
  group_by(shorter_title) %>%
  summarise(count = n())

sort <- full_sample %>%
  left_join(source_num) %>%
  mutate(classification = factor(classification, levels = c("Illustrative", "Evidentiary", "Investigative", "Hybrid", "Experimental"))) %>%
  arrange(classification, count) %>%
  mutate(this_id = row_number()) %>%
  select(shorter_title, classification, this_id)

modality_tile <- modality %>%
  mutate(num = case_when(operative_use == "UV" ~ 1,
                         operative_use == "VIS" ~ 2,
                         operative_use == "PAN" ~ 3,
                         operative_use == "MS" ~ 4,
                         operative_use == "TIR" ~ 5,
                         operative_use == "MW" ~ 6,
                         TRUE ~ 7)) %>%
  left_join(sort) 


ggplot(modality_tile %>% mutate(classification = factor(classification, levels = c("Illustrative", "Evidentiary", "Investigative", "Hybrid", "Experimental"))), aes(x = this_id, y = num, fill = classification)) +
  geom_tile(colour = "white") +
  coord_fixed() +
  scale_x_continuous(
    breaks = 1:44,
    labels = sort$short_title,
  ) +
  scale_y_continuous(
    breaks = 1:6,  
    labels = c("Ultraviolet", "Visible", "Panchromatic", "Multispectral", "Thermal Infratred", "Microwave"),
    minor_breaks = seq(min(modality_tile$this_id) + 0.5, max(modality_tile$this_id) - 0.5)
  ) +
  scale_fill_manual(values = five_point_named) +
  rseo_style() +
  theme(axis.text.y = element_text(size = 10),
        axis.text.x = element_blank(),
        axis.title.x = element_text(),
        axis.ticks.x = element_line(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_line(color = "gray", size = 0.5)
        ) +
  geom_hline(yintercept = 0.5) +
  geom_hline(yintercept = 6.5) +
  labs(x = "Stories in sample")

ggsave("modality_wide.png")


ggplot(modality_tile, aes(x = num, y = this_id, fill = classification)) +
  geom_tile(colour = "white") +
  coord_fixed() +
  scale_x_continuous(
    breaks = 1:6,  
    labels = c("Ultraviolet", "Visible", "Panchromatic", "Multispectral", "Thermal Infrared", "Microwave"),
    minor_breaks = seq(0.5, 6.5, by = 1)  # optional if you want minor grid lines
  ) +
  scale_y_reverse(
    breaks = 1:40 ,
    labels = sort$shorter_title
  ) +
  scale_fill_manual(values = five_point_named) +
  rseo_style() +
  theme(
    axis.text.x = element_text(size = 8, angle = 70, hjust = 1),
    axis.text.y = element_text(size = 6.5),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_line(color = "gray", size = 0.5),
    panel.grid.major.y = element_blank(),
    legend.text = element_text(size = 6.5),
    legend.position = "bottom"
  ) +  geom_vline(xintercept = 6.5)
# +


ggsave("modality_long.png")

ggsave("modality_long.svg")

```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

##subjects 
```{r subjects}

themes <- full_sample %>%
  select(project_title, subject_theme, subject_theme_2, classification) %>%
  pivot_longer(!c(project_title, classification), values_to = "theme") %>%
  drop_na(theme) %>%
  select(project_title, theme, classification)
  

  
themes_filled <- full_sample %>%
  select(project_title, subject_theme, subject_theme_2) %>%
  mutate(subject_theme_2 = ifelse(is.na(subject_theme_2), subject_theme, subject_theme_2)) %>%
  drop_na()

theme_counts <- themes_filled %>%
  count(subject_theme, subject_theme_2) %>%
  mutate(subject_theme = factor(subject_theme, levels = c("War and conflict",
                                          "Human health",
                                          "Extractive industries",
                                          "Urbanism and infrastructure",
                                          "Shipping and logistics",
                                          "Climate and environment")),
         subject_theme_2 = factor(subject_theme_2, levels = c("War and conflict",
                                          "Human health",
                                          "Extractive industries",
                                          "Urbanism and infrastructure",
                                          "Shipping and logistics",
                                          "Climate and environment")))



ggplot(theme_counts, aes(x = subject_theme, y = subject_theme_2, fill = n)) +
  geom_tile(color = "white") +
  geom_text(aes(label = ifelse(n > 0, n, "")), color = "black", size = 3) +
  scale_fill_gradient(low = "grey", high = five_point[2], guide = "none") +
  coord_fixed() +
  rseo_style() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.margin = margin(t = 5, r = 5, b = 5, l = 0),
    axis.text = element_text(size = 10),
    panel.grid.major.y = element_blank()
  ) +
  scale_x_discrete(drop = FALSE) +  # Force all levels to show
  scale_y_discrete(drop = FALSE) +  # Force all levels to show
  # geom_vline(xintercept = seq(0.5, length(unique(theme_counts$subject_theme)), by = 1),
  #          color = "grey80", size = 0.5) +
  # geom_hline(yintercept = seq(0.5, length(unique(theme_counts$subject_theme)), by = 1),
  #          color = "grey80", size = 0.5) +
  geom_vline(xintercept = 0.5, colour = "black") +
  geom_vline(xintercept = 7.5, colour = "black") +
  geom_hline(yintercept = 7.5, colour = "black") +
  geom_hline(yintercept = 0.5, colour = "black")

ggsave("figures/story_themes.png", width = 15, height = 10, units = "cm", dpi = 300)

```


##suppliers 
```{r suppliers}

suppliers <- full_sample %>% select(data_supplier) %>%
  separate_rows(data_supplier, convert = TRUE) %>%
  group_by(data_supplier) %>%
  summarise(count = n()) %>%
  mutate(ownership = ifelse(data_supplier %in% c("ESA", "NASA","INPE","NOAA", "CSA", "ESA", "USGS", "ECMWF", "DMSP"), "Public", "Commercial")) %>%
  mutate(data_supplier = ifelse(data_supplier == "Capella", "Capella Space", data_supplier))


ggplot(suppliers %>% filter(!data_supplier %in% c("Unknown", "Space", "NPP")), aes(x = reorder(data_supplier, count), y = count, fill = ownership)) + 
  geom_col() + 
  coord_flip() +
  rseo_style() +
  geom_vline(xintercept = 0, colour = "black") +
  scale_fill_manual(values = alt_cols_five) +
  theme(panel.grid.major.y = element_blank(),
        axis.text = element_text(size = 10),
        legend.position = "right") 

ggsave("figures/suppliers.png", width = 15, height = 10, units = "cm", dpi = 300)

corrected <- read_csv("to_correct.csv")

supplier_owner <- corrected %>%
  mutate(data_supplier = ifelse(data_supplier == "Capella", "Capella Space", data_supplier),
         derived = ifelse(is.na(derived_data_product), "Primary data", "Secondary dataset"))


supplier_grid <- supplier_owner %>%
  group_by(classification, owner) %>%
  mutate(obs_id = row_number()) %>%
  mutate(n = n(),
         sq = ceiling(sqrt(n))) %>%
  mutate(
    x = ((obs_id - 1) %% sq) + 1,              # x increases across the row
    y = (floor((obs_id - 1) / sq)) + 1         # y increases down the column
  ) %>%
  ungroup()

supplier_grid <- supplier_grid %>%
  mutate(classification = factor(classification,
                                 levels = c("Illustrative", "Evidentiary", "Investigative",
                                            "Hybrid", "Experimental")))
ggplot(supplier_grid, aes(x = x, y = y, fill = derived)) +
  geom_tile(colour = "white") +
  facet_grid(owner ~ classification) +
  scale_fill_manual(values = alt_cols_five) +
  coord_fixed() +  # Keeps squares square
  rseo_style() +
  theme(panel.grid.major.y = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        axis.ticks = element_blank(),
        axis.title =  element_blank(),
        strip.text = element_text(size = 8, hjust = 0))

ratio <- supplier_owner %>% 
  mutate(group = case_when(classification %in% c("Illustrative", "Evidentiary") ~ "low",
                           classification %in% c("Hybrid", "Experimental") ~ "high",
                             TRUE ~ "Mid")) %>%
  group_by(group, owner) %>% count()

ggsave("figures/supplier_grid.png", width = 15, height = 10, units = "cm", dpi = 300)


``` 

##Satellite launches
```{r launches}

purposes <- c("Earth Observation",
              "Earth Observation ",
              "Earth Science",
              "Earth Observation/Technology Development",
              "Communications/Maritime Tracking",
              "Earth Observation/Communications",  
              "Earth Observation/Communications/Space Science",
              "Earth Observation ",
              "Earth Observation/Space Science",
              "Earth Science/Earth Observation",
              "Earth Observation/Earth Science",
              "Surveillance",
              "Earth/Space Observation",
              "Earth Observation/Navigation",
              "Meteorological"
              )



current_names <- c("name_of_satellite_alternate_names",
                   "current_official_name_of_satellite",
                   "country_org_of_un_registry",
                   "country_of_operator_owner",
                   "operator_owner",
                   "users",
                   "purpose",
                   "period_minutes",
                   "perigee_km",
                   "apogee_km",
                   "date_of_launch",
                   "expected_lifetime_yrs",
                   "comments")  



clean_sats <- all_sats %>%
  select(current_names) %>%
  filter(purpose %in% purposes,
         !is.na(date_of_launch) & trimws(date_of_launch) != "") %>%
  mutate(launch = as_date(date_of_launch, format = "%m/%d/%y")) %>%
  group_by(launch) %>%
  arrange(users, .by_group = TRUE) %>%
  mutate(y = row_number()) %>%
  ungroup()


clean_sats_user <- all_sats %>%
  select(current_names) %>%
  filter(purpose %in% purposes,
         !is.na(date_of_launch) & trimws(date_of_launch) != "") %>%
  mutate(launch = as_date(date_of_launch, format = "%m/%d/%y"),
           user_agg = sub("/.*", "", users)) %>%
  group_by(launch, user_agg) %>%
  summarise(count = n()) %>%
  select(launch, user_agg, count) %>%
  ungroup()  %>%
  complete(launch = unique(launch), user_agg = unique(user_agg), fill = list(count = 0)) %>%
  drop_na()


agg_user <- clean_sats_user %>%
  mutate(year_month = floor_date(launch, "year")) %>%
  group_by(year_month, user_agg) %>%
  summarise(count = sum(count), .groups = "drop") %>%
  complete(year_month = seq(min(year_month), max(year_month), by = "year"),
           user_agg = unique(user_agg),
           fill = list(count = 0))

agg_user <- agg_user %>%
  mutate(user_agg = ifelse(user_agg == "Military ", "Military", user_agg))


ggplot(agg_user, aes(x = year_month, y = count, fill = user_agg)) + 
  geom_col() +
  scale_fill_manual(values = rev(seven_point))+
  rseo_style()+
  scale_x_date(
    date_breaks = "1 year",          # one label per year
    date_labels = "%Y",
    expand = c(0, 0), 
  ) +
  theme(legend.position = "right",
        legend.margin = margin (4, 0, 4, 0),
        legend.key.size = unit(1, "char"),
        legend.key.spacing.x = unit(0.7, "char"),
        axis.text.x = element_text(angle = 90, vjust = 0.5)
  )

dpi = 200
ggsave("figures/earth_observation.png", 
       units = "px",
       width = 2000,
       height = 1000,
       dpi = dpi)


``` 


##Spectral Bands
```{r spectral bands}

height_waves = 1
height_bands = 0.5

wavelengths <- wavelengths %>%
  mutate(category = case_when(
           name %in% c("Ultraviolet","Blue","Green","Red","Near infrared","Mid-infrared","Far-infrared","Thermal infrared", "Microwave") ~ "waves",
           T ~ name
         ))%>%
  mutate(factor = as.integer(factor(category, levels = c("waves", unique(category[category != "waves"])))),
         y = if_else(factor <= 2, factor * height_waves, (factor - 2) * height_bands + 2 * height_waves),
         height = if_else(category == "waves", height_waves, height_bands),
         color = if_else(category == "waves", name, NA),
         label = if_else(category == "waves", NA, category),
         labelheight = y + 0.5*height)

color_order <- data %>%
  filter(category == "waves")%>%
  arrange((min_nm))%>%
  pull(name)

y_ticks <- data %>%
  filter(category == "waves")%>%
  select(min_nm, max_nm)%>%
  gather()%>%
  select(value)%>%
  unique()%>%
  mutate(label = case_when(
    value >= 1000000000 ~ glue("{value / 1000000000} m"),
    value >= 1000000 ~ glue("{value / 10000000} cm"),
    T ~ glue("{value} nm")
  ))


ggplot(data, mapping = aes(xmin = min_nm, ymin = y, xmax = max_nm, ymax = y + height - 0.1))+
  geom_rect(mapping = aes(fill = color), color = "black")+
  scale_fill_manual(breaks = c(color_order), 
                    values = c('#d4b0d9', '#0052de', '#72d65d', '#ff434e', '#d3d3d3', '#b7b7b7', '#9b9b9b', '#808080', '#646464'), 
                    na.value = NA,
                    guide = guide_legend(
                      title = NULL,
                      nrow = 1
                    ))+
  scale_x_log10(
    # breaks = y_ticks$value, 
    #             labels = y_ticks$label,
                name  = NULL,
                guide = guide_axis(check.overlap = TRUE))+
  scale_y_continuous(breaks = data$labelheight %>% unique(),
                     labels = data %>% arrange(factor)%>%pull(category)%>%unique(),
                     expand = expansion(0,0),
                     limits = c(-0.5, max(data %>% mutate(top = y + height) %>% pull(top)) + 0.5))+
  geom_text(mapping = aes(x = max_nm, y = labelheight, label = label), hjust = 0, nudge_x = 0.1)+
  geom_text_repel(data = y_ticks, mapping = aes(x = value, y = 1, label = glue(" {label}")),
                  hjust = 0, vjust = 0.5,
                  box.padding = 0.05,
                  inherit.aes = F, ## important!!
                  size = 3.5, nudge_y = -0.5, direction  = "x", angle = -90)+
  rseo_style()+
  theme(panel.grid = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        # axis.ticks.x = element_line(),
        # axis.text.x = element_text(angle= -45, hjust = 0, vjust = 0, margin = margin(5,0,0,0)),
        legend.position = "bottom",
        legend.key.size = unit(1, "char"))

dpi = 100
ggsave("wavelengths_repel.png", 
       width = 1000 / dpi,
       height = 400/dpi)


``` 